# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/School/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.cache/wt} [current_project]
set_property parent.project_path {F:/School/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {F:/School/CMPE140/CMPE140 Lab 1/REGISTER.V}
  {F:/School/CMPE140/CMPE140 Lab 1/MUX.V}
  {F:/School/CMPE140/CMPE140 Lab 1/MUL.V}
  {F:/School/CMPE140/CMPE140 Lab 1/DOWNCOUNTER.V}
  {F:/School/CMPE140/CMPE140 Lab 1/CMP.V}
  {F:/School/CMPE140/CMPE140 Lab 1/BUF.V}
  {F:/School/CMPE140/CMPE140 Lab 1/DP.V}
  {F:/School/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.srcs/sources_1/new/DP_TB.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top DP_TB -part xc7a100tcsg324-1


write_checkpoint -force -noxdef DP_TB.dcp

catch { report_utilization -file DP_TB_utilization_synth.rpt -pb DP_TB_utilization_synth.pb }
