# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/REGISTER.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/MUX.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/MUL.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/DOWNCOUNTER.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMP.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/BUF.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.srcs/sources_1/new/lib.v}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/DP.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CU.V}
  {C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.srcs/sources_1/new/TOP.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/nykos/src/CMPE140/CMPE140 Lab 1/CMPE140 Lab 1/CMPE140 Lab 1.srcs/constrs_1/new/constraints.xdc}}]


synth_design -top TOP -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
